name: Download Node Modules and Create ZIP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.0'  # O la versión que necesites

    - name: Cache Yarn dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.yarn/cache
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Zip node_modules, package-lock.json, and yarn.lock
      run: zip -r project-dependencies.zip node_modules package-lock.json yarn.lock

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: project-dependencies
        path: project-dependencies.zip
